language: node_js

node_js:
  - "6"
  - "8"
  - "node"

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - os: linux
    - os: osx
      node_js: "node"
    - os: windows
      node_js: "node"
  allow_failures:
    - os: osx
    - os: windows
  fast_finish: true

before_install: |
  if [ "${TRAVIS_OS_NAME}" = 'windows' ]; then
    cp test-projects/msdmo.dll /c/Windows/System32/
    npm config set script-shell 'bash'
  fi

script: |
  if [ "${TRAVIS_OS_NAME}" = 'linux' ]; then
    xvfb-run npm test
  else
    npm test
  fi
