sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
addons:
  apt:
    packages:
      - xvfb
      - clang-3.4
install:
  - npm install
  - npm run test-projects-install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
