name: Tests

on:
  - pull_request
  - push

env:
  CI: 1

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        node_version: [latest]
        include:
          - os: ubuntu-latest
            node_version: 8
          - os: macos-latest
            experimental: true
          - os: windows-latest
            experimental: true

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      # Preparing environment
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node_version }}

      - name: Just for the first test
        run: env

      # Preparing OS-specific environment
      - run: npm config set script-shell 'bash'
        if: runner.os == 'Windows'

      - run: sudo apt-get install xvfb
        if: runner.os == 'Linux'

      # Npm install
      - run: npm install

      # Tests
      - run: |
          if [ "${{ matrix.node_version }}" -lt 10 ]; then
            npm run test
          elif [ "${$RUNNER_OS}" = 'Linux' ]; then
            xvfb-run --auto-servernum npm run test:full
          else
            npm run test:full
          fi

      - uses: bcomnes/cleanup-xvfb@v1
